dependencies:
  - scipy
  - matplotlib
  - numpy
  - AstroML
  - healpy
  - sympy
  - quantities
  - ghostscript
  - texlive-core
  - pip
  - pytest
  - ipywidgets >= 6.0.0
  - pip:
      - julia
      - nbval
      - nbdime
